### ISSUE TITLE
clockid_t and clock_gettime

### ISSUE THREAD

**Issue by Armael** [dsheets/ocaml-unix-time#1]
I would like (need) to add bindings to `clock_gettime` and hence `clockid_t`. However I don't know how to do that in a platform independent way: the [documentation](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html) says that `clockid_t` should exist, but doesn't seem to define what it should be (so I guess the precise implementation is platform specific?). What's the right solution using ctypes?

**Comment by yallop** [comment]
There used to be a [binding to `clockid_t`](https://github.com/yallop/ocaml-posix-types/blob/cd5f2d1e00142923f9699219438a79a59fca4a32/lib/posix_types.mli#L135) in the [posix-types](https://github.com/yallop/ocaml-posix-types/) package, but it was removed because OS X didn't support that type.

**Comment by Armael** [comment]
Ah, I see... What would be the right way of reusing the infrastructure of posix-types for type info discovery, and exposing `clockid_t` where it is available? Could there be a linux-specific (or unix-but-not-osx-specific?) sub-package of posix-types?

**Comment by Armael** [comment]
On the other hand, it may not be worth the hassle, and I could probably just use an ocaml time library (mtime?) and convert to `Timespec.t`.

**Comment by Armael** [comment]
I just noticed that mtime is implemented using `clock_gettime(CLOCK_MONOTONIC,...)` on linux. So I should be fine with just converting the output of mtime to `Timespec.t` :).
